### ISSUE TITLE
About Queuing systems

### ISSUE THREAD

**Issue by srmnitc** [pyiron/pylammpsmpi#15]
@jan-janssen Any idea how we could possibly run this on a queuing system? As in information should still be accessible through a jupyter notebook, but the run for example should be on a queue.

**Comment by jan-janssen** [comment]
In pyiron we run the jobs on the login node until the example is working - for example with a smaller system size and afterwards we submit the notebook to the queuing system using the Skriptjob class https://github.com/pyiron/pyiron/blob/master/pyiron/base/job/script.py . This two step process is not interactive but all the other solutions we came up with otherwise like communicating via sockets are forbidden on most clusters.

**Comment by jan-janssen** [comment]
I did some more research and I guess the most productive solution would be using sockets, an example can be found here:
https://pythonprogramming.net/pickle-objects-sockets-tutorial-python-3/
There is already a software package based on this idea:
http://ipi-code.org/
But that one is based on cryptic xml input files, so if we can do the same on a python level that would be great. In terms of submitting to the queuing system, we already released the pyiron queuing adapter as a separate package, so I would recommend to use that one. 
https://github.com/pyiron/pysqa

**Comment by jan-janssen** [comment]
I started a new branch with a draft for the socket interface https://github.com/pyiron/pylammpsmpi/tree/socket - not tested yet.
