### ISSUE TITLE
[Bug] Test core dependency 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pylammpsmpi#41]
Like we discussed during the pyiron meeting, it would be interesting to see what happens when DASK only gets a single core and then still calls Lammps via the MPI subprocess with more than one core.

**Comment by jan-janssen** [comment]
I tried: 

```
cluster = LocalCluster(n_workers=1, threads_per_worker=1)
```

and 

```
lmp = LammpsLibrary(cores=8, mode='dask', client=client)
```

In the current version of https://github.com/pyiron/pylammpsmpi/blob/master/notebooks/lammps_local_cluster.ipynb 
and it worked. This means with the subprocess we are tricking dask to believe a function is only using a single core while it is actually using multiple cores.

**Comment by srmnitc** [comment]
I explored this a bit. So this is possible because we are using an `oversubscribe` option with `mpirun`. If we remove it, however, it won't work at all. `mpirun` for some reason it thinks there is only one core available when running with `dask`. I do not know exactly why or if this can be fixed, but for now this behavior will continue. One has to make sure the number of cores passed to `pylammpmpi` matches that of the `dask` cluster. I will look into it a bit more closely when I have time.

**Comment by jan-janssen** [comment]
I have the feeling that is an issue with DASK, that they do not expect DASK tasks to use MPI. Maybe you can talk to their developers about this.

**Comment by jan-janssen** [comment]
The only thing I found in this direction so far is https://blog.dask.org/2019/01/31/dask-mpi-experiment

**Comment by srmnitc** [comment]
yeah, I saw this one too. I will check a bit more closely. I can also try to contact some of the developers.
